# Generated by Django 5.0.6 on 2024-07-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
